import { Plus, ShoppingCart } from "lucide-react"
import { createPurchaseOrder, updatePurchaseOrderStatus } from "@/app/actions"
import { SelectField } from "@/components/shared/Field"
import { FormDialog } from "@/components/shared/FormDialog"
import { DataNotice } from "@/components/shared/DataNotice"
import { DataTable, type Column } from "@/components/shared/DataTable"
import { StatCard } from "@/components/shared/StatCard"
import { StatusBadge } from "@/components/shared/StatusBadge"
import { Button } from "@/components/ui/button"
import { getEmployees, getPurchaseOrders, getSuppliers, type PurchaseOrderRow } from "@/lib/queries"
const columns: Column<PurchaseOrderRow>[] = [{ header: "Order", accessorKey: "po_id", sortable: true, cell: (row) => `PO #${row.po_id}` }, { header: "Supplier", accessorKey: "supplier_name", sortable: true }, { header: "Officer", accessorKey: "officer_name" }, { header: "Date", accessorKey: "orderdate", cell: (row) => new Date(row.orderdate).toLocaleDateString("en-UG") }, { header: "Status", accessorKey: "status", cell: (row) => <StatusBadge status={row.status as "Pending" | "Approved" | "Received" | "Cancelled"} /> }]
export default async function PurchaseOrdersPage() { const [orders, suppliers, employees] = await Promise.all([getPurchaseOrders(), getSuppliers(), getEmployees()]); const officers = employees.data.filter((employee) => employee.roletype === "Procurement Officer"); const counts = (status: string) => orders.data.filter((order) => order.status === status).length; return <div className="grid gap-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-semibold">Purchase orders</h1><p className="text-muted-foreground">The deployed schema stores order headers only; totals and line items are intentionally not shown.</p></div><FormDialog title="Create purchase order" description="Create a Pending order with an existing supplier and procurement officer." trigger={<Button><Plus /> New order</Button>} action={createPurchaseOrder} submitLabel="Create order"><SelectField label="Supplier" name="supplierid" required><option value="">Select supplier</option>{suppliers.data.map((supplier) => <option key={supplier.supplierid} value={supplier.supplierid}>{supplier.suppliername}</option>)}</SelectField><SelectField label="Procurement officer" name="employeeid" required><option value="">Select officer</option>{officers.map((officer) => <option key={officer.employeeid} value={officer.employeeid}>{officer.name}</option>)}</SelectField></FormDialog></div><DataNotice {...orders} /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard title="All orders" value={orders.data.length} icon={<ShoppingCart />} /><StatCard title="Pending" value={counts("Pending")} icon={<ShoppingCart className="text-amber-500" />} /><StatCard title="Approved" value={counts("Approved")} icon={<ShoppingCart className="text-primary" />} /><StatCard title="Received" value={counts("Received")} icon={<ShoppingCart className="text-emerald-500" />} /></div><section className="grid gap-3"><DataTable data={orders.data} columns={columns} searchKey="supplier_name" rowKey={(row) => row.po_id} emptyMessage="No purchase orders yet." /><div className="rounded-xl border bg-card p-4"><h2 className="mb-3 font-medium">Change order status</h2><form action={updatePurchaseOrderStatus} className="grid gap-3 sm:grid-cols-3"><SelectField label="Purchase order" name="po_id" required><option value="">Select order</option>{orders.data.map((order) => <option key={order.po_id} value={order.po_id}>PO #{order.po_id} · {order.supplier_name}</option>)}</SelectField><SelectField label="New status" name="status" required><option value="Pending">Pending</option><option value="Approved">Approved</option><option value="Received">Received</option><option value="Cancelled">Cancelled</option></SelectField><Button className="self-end">Update status</Button></form></div></section></div> }
