import { Link2, Plus, Truck } from "lucide-react"
import { createSupplier, createSupply } from "@/app/actions"
import { Field, SelectField } from "@/components/shared/Field"
import { FormDialog } from "@/components/shared/FormDialog"
import { DataNotice } from "@/components/shared/DataNotice"
import { DataTable, type Column } from "@/components/shared/DataTable"
import { StatCard } from "@/components/shared/StatCard"
import { Button } from "@/components/ui/button"
import { getProducts, getSuppliers, getSupply, type SupplierRow, type SupplyRow } from "@/lib/queries"
const money = (value: number) => new Intl.NumberFormat("en-UG", { style: "currency", currency: "UGX", maximumFractionDigits: 0 }).format(value)
const supplierColumns: Column<SupplierRow>[] = [{ header: "Supplier", accessorKey: "suppliername", sortable: true }, { header: "Contact", accessorKey: "contactperson", cell: (row) => row.contactperson ?? "—" }, { header: "Phone", accessorKey: "phone", cell: (row) => row.phone ?? "—" }, { header: "Address", accessorKey: "address", cell: (row) => row.address ?? "—" }]
const supplyColumns: Column<SupplyRow>[] = [{ header: "Supplier", accessorKey: "supplier_name", sortable: true }, { header: "Product", accessorKey: "item_name", sortable: true }, { header: "Cost price", accessorKey: "costprice", cell: (row) => money(row.costprice) }, { header: "Lead time", accessorKey: "leadtimedays", cell: (row) => row.leadtimedays === null ? "—" : `${row.leadtimedays} days` }]
export default async function SuppliersPage() { const [suppliers, products, supply] = await Promise.all([getSuppliers(), getProducts(), getSupply()]); return <div className="grid gap-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-semibold">Suppliers & supply catalogue</h1><p className="text-muted-foreground">Maintain vendors and the products each vendor can provide.</p></div><div className="flex gap-2"><FormDialog title="Link a supplier to a product" description="Creates a row in the supply associative table." trigger={<Button variant="outline"><Link2 /> Add supply link</Button>} action={createSupply} submitLabel="Save link"><SelectField label="Supplier" name="supplierid" required><option value="">Select supplier</option>{suppliers.data.map((supplier) => <option key={supplier.supplierid} value={supplier.supplierid}>{supplier.suppliername}</option>)}</SelectField><SelectField label="Product" name="itemid" required><option value="">Select product</option>{products.data.map((product) => <option key={product.itemid} value={product.itemid}>{product.itemname}</option>)}</SelectField><div className="grid grid-cols-2 gap-3"><Field label="Cost price (UGX)" name="costprice" type="number" min="0" required /><Field label="Lead time (days)" name="leadtimedays" type="number" min="0" /></div></FormDialog><FormDialog title="Add supplier" description="Register a vendor before linking supplied products." trigger={<Button><Plus /> Add supplier</Button>} action={createSupplier} submitLabel="Add supplier"><Field label="Supplier name" name="suppliername" required /><Field label="Contact person" name="contactperson" /><Field label="Phone" name="phone" type="tel" /><Field label="Address" name="address" /></FormDialog></div></div><DataNotice {...suppliers} /><div className="grid gap-4 sm:grid-cols-2"><StatCard title="Suppliers" value={suppliers.data.length} icon={<Truck />} /><StatCard title="Supplier-product links" value={supply.data.length} icon={<Link2 />} /></div><section className="grid gap-3"><h2 className="font-medium">Suppliers</h2><DataTable data={suppliers.data} columns={supplierColumns} searchKey="suppliername" rowKey={(row) => row.supplierid} emptyMessage="No suppliers registered yet." /></section><section className="grid gap-3"><h2 className="font-medium">Supply catalogue</h2><DataTable data={supply.data} columns={supplyColumns} searchKey="item_name" rowKey={(row) => `${row.supplierid}-${row.itemid}`} emptyMessage="No supplier-product links yet." /></section></div> }
