"use client"
import { useState } from "react"
import { createEmployee } from "@/app/actions"
import { Field, SelectField } from "@/components/shared/Field"
import { FormDialog } from "@/components/shared/FormDialog"
import { Button } from "@/components/ui/button"
import { Plus } from "lucide-react"

type Branch = { branchid: number; branchname: string }; type Department = { departmentid: number; departmentname: string; branchid: number }; type Employee = { employeeid: number; name: string }
export function EmployeeForm({ branches, departments, employees }: { branches: Branch[]; departments: Department[]; employees: Employee[] }) { const [role, setRole] = useState("Cashier"); return <FormDialog title="Add employee" description="Creates the employee record and its role-specific subtype row." trigger={<Button><Plus /> Add employee</Button>} action={createEmployee} submitLabel="Save employee" className="sm:max-w-2xl"><div className="grid gap-3 sm:grid-cols-2"><Field label="Full name" name="name" required /><Field label="National ID (NIN)" name="nin" required /><Field label="Phone" name="phone" type="tel" /><Field label="Date hired" name="datehired" type="date" /><Field label="Salary (UGX)" name="salary" type="number" min="0" required /><label className="grid gap-1.5 text-sm font-medium">Role<select className="h-8 rounded-lg border bg-background px-2.5 text-sm" value={role} onChange={(event) => setRole(event.target.value)}><option value="Cashier">Cashier</option><option value="Procurement Officer">Procurement Officer</option><option value="Accountant">Accountant</option><option value="HR Staff">HR Staff</option><option value="Branch Manager">Branch Manager</option></select></label><SelectField label="Branch" name="branchid" required><option value="">Select branch</option>{branches.map((branch) => <option key={branch.branchid} value={branch.branchid}>{branch.branchname}</option>)}</SelectField><SelectField label="Department" name="departmentid" required><option value="">Select department</option>{departments.map((department) => <option key={department.departmentid} value={department.departmentid}>{department.departmentname}</option>)}</SelectField><SelectField label="Supervisor (optional)" name="supervisorid"><option value="">No supervisor</option>{employees.map((employee) => <option key={employee.employeeid} value={employee.employeeid}>{employee.name}</option>)}</SelectField></div><div className="rounded-lg border bg-muted/40 p-3 text-sm"><input type="hidden" name="roletype" value={role} />{role === "Cashier" && <Field label="POS terminal ID" name="pos_terminalid" required />}{role === "Procurement Officer" && <Field label="Approval limit (UGX)" name="approvallimit" type="number" min="0" required />}{role === "Accountant" && <Field label="Certification number" name="certificationnumber" />}{role === "HR Staff" && <Field label="HR role" name="hr_role" required />}{role === "Branch Manager" && <Field label="Management level" name="managementlevel" />}</div></FormDialog> }
