import { BookOpen, Plus } from "lucide-react"
import { createLedgerEntry } from "@/app/actions"
import { Field, SelectField } from "@/components/shared/Field"
import { FormDialog } from "@/components/shared/FormDialog"
import { DataNotice } from "@/components/shared/DataNotice"
import { DataTable, type Column } from "@/components/shared/DataTable"
import { StatCard } from "@/components/shared/StatCard"
import { Button } from "@/components/ui/button"
import { getEmployees, getLedger, getPayroll, getSales, type LedgerRow } from "@/lib/queries"
const money = (value: number) => new Intl.NumberFormat("en-UG", { style: "currency", currency: "UGX", maximumFractionDigits: 0 }).format(value)
const columns: Column<LedgerRow>[] = [{ header: "Date", accessorKey: "entrydate", sortable: true, cell: (row) => new Date(row.entrydate).toLocaleDateString("en-UG") }, { header: "Source type", accessorKey: "sourcetype", sortable: true }, { header: "Source", accessorKey: "source_label" }, { header: "Amount", accessorKey: "amount", cell: (row) => money(row.amount) }, { header: "Recorded by", accessorKey: "accountant_name" }]
export default async function LedgerPage() { const [ledger, sales, payroll, employees] = await Promise.all([getLedger(), getSales(), getPayroll(), getEmployees()]); const accountants = employees.data.filter((employee) => employee.roletype === "Accountant"); return <div className="grid gap-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-semibold">Ledger</h1><p className="text-muted-foreground">Record an amount against exactly one completed sale or payroll record.</p></div><FormDialog title="Add ledger entry" description="The selected source determines whether sale ID or payroll ID is saved." trigger={<Button><Plus /> Add entry</Button>} action={createLedgerEntry} submitLabel="Save entry"><SelectField label="Source type" name="sourcetype" required><option value="SALE">Sale</option><option value="PAYROLL">Payroll</option></SelectField><SelectField label="Sale ID (required for Sale source)" name="saleid"><option value="">Select sale</option>{sales.data.map((sale) => <option key={sale.saleid} value={sale.saleid}>Sale #{sale.saleid} · {money(sale.totalamount)}</option>)}</SelectField><SelectField label="Payroll ID (required for Payroll source)" name="payrollid"><option value="">Select payroll</option>{payroll.data.map((row) => <option key={row.payrollid} value={row.payrollid}>{row.employee_name} · {row.month}</option>)}</SelectField><Field label="Amount (UGX)" name="amount" type="number" min="0" required /><SelectField label="Recorded by (accountant)" name="recordedby" required><option value="">Select accountant</option>{accountants.map((accountant) => <option key={accountant.employeeid} value={accountant.employeeid}>{accountant.name}</option>)}</SelectField></FormDialog></div><DataNotice error={ledger.error ?? sales.error ?? payroll.error ?? employees.error} rlsBlocked={ledger.rlsBlocked || sales.rlsBlocked || payroll.rlsBlocked || employees.rlsBlocked} /><div className="grid gap-4 sm:grid-cols-2"><StatCard title="Ledger entries" value={ledger.data.length} icon={<BookOpen />} /></div><DataTable data={ledger.data} columns={columns} searchKey="source_label" rowKey={(row) => row.entryid} emptyMessage="No ledger entries yet." /></div> }
